### ISSUE TITLE
I couldn't find the board 

### ISSUE THREAD

**Issue by ahmedwahdan** [AndreAhmed/STMF32GameConsole#1]
Could you please provide a link to the board used and the screen.
Thanks.

**Comment by AndreAhmed** [comment]
https://www.amazon.com/32F429IDISCOVERY-STM32F429I-DISCO-Discovery-STM32F429ZIT6-Development/dp/B01EJ3GEJO/ref=sr_1_1?ie=UTF8&qid=1528733414&sr=8-1&keywords=stm32f4+disco
